// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASM3zEnsjt0hBnw3C3HTeD1XEUr2ZZ9Ok',
    appId: '1:1005797337828:web:fffe855a8cac33c4845af1',
    messagingSenderId: '1005797337828',
    projectId: 'mobile-app-7318e',
    authDomain: 'mobile-app-7318e.firebaseapp.com',
    storageBucket: 'mobile-app-7318e.firebasestorage.app',
    measurementId: 'G-4R2GK3HE02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeHY_b0tFDOrtgjb2qNOpehxC1mZzr0AQ',
    appId: '1:1005797337828:android:0b648a679cc523d6845af1',
    messagingSenderId: '1005797337828',
    projectId: 'mobile-app-7318e',
    storageBucket: 'mobile-app-7318e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxtu3pgV4Qho_ua05uaOYp_GAqKAjsCGc',
    appId: '1:1005797337828:ios:9b638c23a6b65544845af1',
    messagingSenderId: '1005797337828',
    projectId: 'mobile-app-7318e',
    storageBucket: 'mobile-app-7318e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxtu3pgV4Qho_ua05uaOYp_GAqKAjsCGc',
    appId: '1:1005797337828:ios:9b638c23a6b65544845af1',
    messagingSenderId: '1005797337828',
    projectId: 'mobile-app-7318e',
    storageBucket: 'mobile-app-7318e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASM3zEnsjt0hBnw3C3HTeD1XEUr2ZZ9Ok',
    appId: '1:1005797337828:web:32f3b3b7046e631d845af1',
    messagingSenderId: '1005797337828',
    projectId: 'mobile-app-7318e',
    authDomain: 'mobile-app-7318e.firebaseapp.com',
    storageBucket: 'mobile-app-7318e.firebasestorage.app',
    measurementId: 'G-P1V7SNXB09',
  );
}
